cc_test(
    name = "slog_cc_test",
    srcs = ["slog_test.cc"],
    deps = [
        "@com_github_google_googletest//:gtest_main",
        "@slog//:slog_cc",
        "@analysis_tools/tracing::slog_trace_subsriber.h"
    ],
)
