name: learn-github-actions
on: [push]
jobs:
  test-and-build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: "scripts/setup_dev_env.sh"
      - run: "bazelisk test --test_output=errors //..."
      - run: "bazelisk build //..."
 
  # TODO(viktor): make linter in CI and my machine work equally and enable lint step in CI. 
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: "scripts/install_linters.sh && scripts/lint.sh ./"

  # TODO(viktor): upload file to some temp storage? ideally github with 30 days TTL
  # package-slog-repo-zip:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: "sudo apt update"
  #     - run: "sudo apt install zip -y"
  #     - run: "pkg_slog_repo_zip/zip_and_upload_to_artifactory.sh $(cat VERSION).${BUILDKITE_BUILD_NUMBER}"

  # TODO(viktor): upload file to some temp storage? ideally github with 30 days TTL
  # package-slog-py-wheel:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: "scripts/setup_dev_env.sh"
  #     - run: "sudo apt update"
  #     - run: "sudo apt install twine -y"
  #     - run: "cd pkg_slog_py_wheel && ./prepare_build.sh $(cat ../VERSION).${BUILDKITE_BUILD_NUMBER} && ./pypi_nexus_login.sh"
  #     - run: "bazelisk build //pkg_slog_py_wheel:slog_py"

#   - label: ":hammer: AUTOSAR compliance check (errors)"
#     timeout: 5
#     agents:
#       queue: cpu-large
#     # TODO(vsbus): add steps for `warning` and all (i.e. empty args)
#     command: scripts/arene_autosar_check.sh error
#     soft_fail:
#       - exit_status: 1
#     retry:
#       <<: *retries
#     plugins:
#       <<: *vault
#       <<: *docker

# TODO(viktor): add wait of above steps and enable import tests:
#  - wait

  test-import-slog_cc-via-bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: "scripts/setup_dev_env.sh"
      - run: |
          cd test_import/example_project_cc_via_bazel/ && \
          ./prepare_workspace.sh $(git log | head -1 | awk '{print($2)}') && \
          bazelisk test --test_output=errors src:slog_cc_test

  test-import-slog_py-via-bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: "scripts/setup_dev_env.sh"
      - run: |
          cd test_import/example_project_py_via_bazel/ && \
          ./prepare_workspace.sh $(git log | head -1 | awk '{print($2)}') && \
          bazelisk test --test_output=errors src:slog_py_test

#  - label: ":rocket: System Test: Import slog_py via pip"
#    timeout: 5
#    agents:
#      queue: cpu-small
#    commands:
#      - "cd test_import/example_project_py_via_pip/"
#      - "scripts/setup_env.sh $(cat ../../VERSION).${BUILDKITE_BUILD_NUMBER}"
#      - "python src/slog_test.py"
#    retry:
#      <<: *retries
#    plugins:
#      <<: *vault
#      <<: *docker
